### ISSUE TITLE
Failed to sync files

### ISSUE THREAD

**Issue by ricky136973** [BoYanZh/Canvas-Syncer#11]
My syncer prompts the following error whenever I try to sync:
```
Unexpected Error: RetryError. Please check your network and your token!
```

**Comment by BoYanZh** [comment]
Please update to the latest version, use `-d` as argument, run it and attach the information.

**Comment by ricky136973** [comment]
I've been using the version `1.2.4` and the syncer cannot recognize the argument `-d`.
```
user@SJTU-CACTUS:~$ canvassyncer -V
1.2.4
user@SJTU-CACTUS:~$ canvassyncer -d
usage: canvassyncer [-h] [-r] [-y] [-p PATH] [-x PROXY] [-V]
canvassyncer: error: unrecognized arguments: -d
```

**Comment by BoYanZh** [comment]
Version `1.2.4` is not the lastest version.

**Comment by ricky136973** [comment]
I've just successfully upgraded to version `1.2.9` and here's the info:
```
user@SJTU-CACTUS:~$ canvassyncer -d
Get 9 available courses!
Finding files on canvas...
Unexpected Error: RetryError. Please check your network and your token!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 817, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 817, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 817, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 807, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='umjicanvas.com', port=443): Max retries exceeded with url: /files/81280/download?download_frd=1&verifier=I7VdmLf61b9mKvyNTcEpfn5wPQXoC4SaoYxxYFYC (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/canvassyncer/__main__.py", line 495, in run
    Syncer.sync()
  File "/usr/local/lib/python3.8/dist-packages/canvassyncer/__main__.py", line 393, in sync
    self.checkNewFiles()
  File "/usr/local/lib/python3.8/dist-packages/canvassyncer/__main__.py", line 335, in checkNewFiles
    for info in self.getCourseTaskInfo(courseID):
  File "/usr/local/lib/python3.8/dist-packages/canvassyncer/__main__.py", line 306, in getCourseTaskInfo
    response = self.sessHead(fileUrl)
  File "/usr/local/lib/python3.8/dist-packages/canvassyncer/__main__.py", line 187, in sessHead
    return self.sess.head(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 565, in head
    return self.request('HEAD', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='umjicanvas.com', port=443): Max retries exceeded with url: /files/81280/download?download_frd=1&verifier=I7VdmLf61b9mKvyNTcEpfn5wPQXoC4SaoYxxYFYC (Caused by ResponseError('too many 500 error responses'))
```

**Comment by ricky136973** [comment]
After having read the debug info and having reset the configurations for several times to sync different courses separately I now find the problem. The file with id `81280` of the course ` Undergraduate Students` keeps returning `500` upon downloads, which I believe is the issue of the server. My current solution is to simply ignore this course. With regard to such situation the syncer might have skipped the single file when certain exception is caught. I may check the source when I' free to see if I could implement my idea. Anyway this issue is closed. Thanks for your guidance.
