### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by jhinpan** [BoYanZh/Canvas-Syncer#32]
I wonder how to fix the bug appearing today in my canvassyncer:
"Unexpected Error: FileNotFoundError. Please check your network and your token".
But I've checked my network and updated my token. This bug still exists.

**Comment by BoYanZh** [comment]
try to run it with `-d` to show debug output and paste it here.

**Comment by jhinpan** [comment]
C:\Users\jpan1221>canvassyncer -d
Get 5 available courses!
Finding files on canvas...
Unexpected Error: FileNotFoundError. Please check your network and your token!
Traceback (most recent call last):
  File "c:\users\jpan1221\appdata\local\programs\python\python38\lib\site-packages\canvassyncer\__main__.py", line 495, in run
    Syncer.sync()
  File "c:\users\jpan1221\appdata\local\programs\python\python38\lib\site-packages\canvassyncer\__main__.py", line 393, in sync
    self.checkNewFiles()
  File "c:\users\jpan1221\appdata\local\programs\python\python38\lib\site-packages\canvassyncer\__main__.py", line 335, in checkNewFiles
    for info in self.getCourseTaskInfo(courseID):
  File "c:\users\jpan1221\appdata\local\programs\python\python38\lib\site-packages\canvassyncer\__main__.py", line 285, in getCourseTaskInfo
    self.createFolders(courseID, folders)
  File "c:\users\jpan1221\appdata\local\programs\python\python38\lib\site-packages\canvassyncer\__main__.py", line 197, in createFolders
    os.makedirs(path)
  File "c:\users\jpan1221\appdata\local\programs\python\python38\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\jpan1221\appdata\local\programs\python\python38\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\Canvassyncer_22Sum\\VE401/Quiz Files/ve401-probabilistic-methods-in-eng-quiz-export_3498/Quiz Files/ve401-probabilistic-methods-in-eng-quiz-export_1040/Quiz Files/ve401-probabilistic-methods-in-eng-quiz-export_939/Quiz Files/ve401-probabilistic-methods-in-eng-quiz-export_768'

This is an error caused by this file? Now prof. Horst has deleted this file. And after I delete it in the synced file, the same error still occurs.

**Comment by BoYanZh** [comment]
Yes. I think it is caused by the path being so long that it exceeds the upper limit of windows.

https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

And does that path exist on canvas?

**Comment by jhinpan** [comment]
No, that path has been deleted in canvas. But something strange happens, each time I run canvassyncer, this path would still occur even though deleted it.

**Comment by jhinpan** [comment]
After enabling the long path in windows 10, the canvassyncer can work again! Thanks a lot!!
