### ISSUE TITLE
TypeError on every run

### ISSUE THREAD

**Issue by Linus-XZX** [BoYanZh/Canvas-Syncer#36]
Environment: macOS Monterey 12.5.1 (21G83), Homebrew Python 3.10.6_1, pip 22.2.2 `from /usr/local/lib/python3.10/site-packages/pip (python 3.10)`, Canvassyncer 2.0.7 (installed with `pip3.10 install canvassyncer`)

Output from `canvassyncer -d`:

> Getting course IDs...
Unexpected error: TypeError. Please check your network and token!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 454, in sync
    await syncer.sync()
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 309, in sync
    await self.getCourseID()
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 212, in getCourseID
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 187, in getCourseIdByCourseCode
    self.courseCode = await self.dictFromPages(
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 110, in dictFromPages
    pageRes = await asyncio.gather(
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 176, in getCourseIdByCourseCodeHelper
    courses = await self.client.json(url, checkError=True)
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 61, in json
    resp = await self.client.get(*args, **kwargs)
TypeError: AsyncClient.get() got an unexpected keyword argument 'checkError'

> Traceback (most recent call last):
  File "/usr/local/bin/canvassyncer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__init__.py", line 5, in main
    run()
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 484, in run
    asyncio.run(sync())
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 477, in sync
    await syncer.aclose()
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 103, in aclose
    await self.client.aclose()
  File "/usr/local/lib/python3.10/site-packages/canvassyncer/__main__.py", line 79, in aclose
    await self.client.aclose()
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1968, in aclose
    await self._transport.aclose()
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 365, in aclose
    await self._pool.aclose()
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 1 HTTP requests/responses were still in-flight.

`.canvassyncer.json` for reference:

> {
    "canvasURL": "https://jicanvas.com",
    "token": "_[omitted]_",
    "courseCodes": [
        "VE281",
        "VE311",
        "VE370",
        "VG496"
    ],
    "courseIDs": [
        1884
    ],
    "downloadDir": "/Users/linus_xu/OneDrive - sjtu.edu.cn/Canvas",
    "filesizeThresh": 250
}

It appears that the problem persists even when I reconfigure it to work with the old Canvas site. And I can guarantee that the tokens are correctly set in either case.

**Comment by BoYanZh** [comment]
Should have been fixed in v2.0.9.

**Comment by Linus-XZX** [comment]
Resolved.
