### ISSUE TITLE
Unexpected error: JSONDecodeError. Please check your network and token!

### ISSUE THREAD

**Issue by Yushu-He** [BoYanZh/Canvas-Syncer#38]
# Bug describe
I checked my network and token and am sure that they are all without any problem. But I still get this error.
Here is the detailed debug information.
```
~>canvassyncer -d
Getting course IDs...
Unexpected error: JSONDecodeError. Please check your network and token!
Traceback (most recent call last):
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 445, in sync
    await syncer.sync()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 306, in sync
    await self.getCourseID()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 209, in getCourseID
    await asyncio.gather(*coros)
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 184, in getCourseIdByCourseCode
    self.courseCode = await self.dictFromPages(
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 107, in dictFromPages
    pageRes = await asyncio.gather(
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 173, in getCourseIdByCourseCodeHelper
    courses = await self.client.json(url, checkError=True)
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 63, in json
    res = resp.json()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\httpx\_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "E:\msys64\mingw64\lib\python3.10\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "E:\msys64\mingw64\lib\python3.10\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

Traceback (most recent call last):
  File "E:\msys64\mingw64\lib\python3.10\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\msys64\mingw64\lib\python3.10\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\msys64\mingw64\bin\canvassyncer.exe\__main__.py", line 7, in <module>
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__init__.py", line 5, in main
    run()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 474, in run
    asyncio.run(sync())
  File "E:\msys64\mingw64\lib\python3.10\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\msys64\mingw64\lib\python3.10\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 467, in sync
    await syncer.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 100, in aclose
    await self.client.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 76, in aclose
    await self.client.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\httpx\_client.py", line 1968, in aclose
    await self._transport.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\httpx\_transports\default.py", line 365, in aclose
    await self._pool.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\httpcore\_async\connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 12 HTTP requests/responses were still in-flight.
```
And when I only add *one* course to the configuration, everything is fine.
```
~>canvassyncer -r
Generating new config file...
Canvas url(Default: https://jicanvas.com):
Canvas access token(Default: omitted):
Courses to sync in course codes(split with space)(Default: PHYS2500J PHYS2410J MATH2860J MATH2860J ECE2800J MARX1205): PHYS2500J
Courses to sync in course ID(split with space)(Default: 170 168 77 130 113 164): 170
Path to save canvas files(Default: E:\Desktop):
Maximum file size to download(MB)(Default: 250.0):
Getting course IDs...
Get 1 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
```
Things became strange when I attempted to add more courses
```
~>canvassyncer -r
Generating new config file...
Canvas url(Default: https://jicanvas.com):
Canvas access token(Default: ): omitted
Courses to sync in course codes(split with space)(Default: PHYS2500J): PHYS2500J MATH2860J
Courses to sync in course ID(split with space)(Default: 170): 170 77
Path to save canvas files(Default: E:\Desktop):
Maximum file size to download(MB)(Default: 250.0):
Getting course IDs...
Get 2 available courses!
Finding files on canvas...
Unexpected error: JSONDecodeError. Please check your network and token! Or use -d for detailed information.
Traceback (most recent call last):
  File "E:\msys64\mingw64\lib\python3.10\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\msys64\mingw64\lib\python3.10\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\msys64\mingw64\bin\canvassyncer.exe\__main__.py", line 7, in <module>
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__init__.py", line 5, in main
    run()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 474, in run
    asyncio.run(sync())
  File "E:\msys64\mingw64\lib\python3.10\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\msys64\mingw64\lib\python3.10\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 467, in sync
    await syncer.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 100, in aclose
    await self.client.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer\__main__.py", line 76, in aclose
    await self.client.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\httpx\_client.py", line 1968, in aclose
    await self._transport.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\httpx\_transports\default.py", line 365, in aclose
    await self._pool.aclose()
  File "E:\msys64\mingw64\lib\python3.10\site-packages\httpcore\_async\connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 14 HTTP requests/responses were still in-flight.
```
# Detailed system and environment information
- OS: win10
- python Version: 3.10.5
- pip Version: 22.2.2
- canvassyncer version: 2.0.9 (installed through pip)

I would truly appreciate it if anyone can help me solve this issue.

**Comment by wznmickey** [comment]
The server have stronger limit on request. 
Is solving in https://github.com/BoYanZh/Canvas-Syncer/pull/35

--update

Solved in the latest version(2.0.10)

**Comment by Yushu-He** [comment]
I updated it to version 2.0.10 and regenerated the configuration, but it seems that the program is not working. 
```
~>canvassyncer -d
Getting course IDs...
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
Get 0 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
```
I am sure that VE215 has a syllabus in the files and the program even didn't generate a directory "ECE2150J" for it

**Comment by wznmickey** [comment]
what course code do you input？
It seems that there is no course found.

**Comment by Yushu-He** [comment]
It created two empty directories after running. "PHYS2500J" and "MARX1205"
```
\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> 
cat .\.canvassyncer.json
{
    "canvasURL": "https://jicanvas.com",
    "token": "omitted",
    "courseCodes": [
        "VP250",
        "VV286",
        "VE215",
        "VE280",
        "VP241",
        "TH020"
    ],
    "courseIDs": [
        170,
        77,
        130,
        113,
        168,
        164
    ],
    "downloadDir": "omitted",
    "filesizeThresh": 250.0
}
```
And it seems to be working after I tried for more times
```
PS E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> canvassyncer -d
Getting course IDs...
Get 1 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
PS E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> canvassyncer -d
Getting course IDs...
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
Get 0 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
PS E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> canvassyncer -d
Getting course IDs...
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
Get 0 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
PS E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> canvassyncer -d
Getting course IDs...
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
Get 2 available courses!
Finding files on canvas...
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 2 times.
JSONDecodeError. Retry. 2 times.
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 2 times.
JSONDecodeError. Retry. 2 times.
Get 1 files!
Start to download 1 file(s)!
ECE2150J/Syllabus VE215 Introduction to Circuits (2022 Fall).pdf (0.32MB)
100%|███████████████████████████████████████████████████████████████████████████████| 324k/324k [00:00<00:00, 3.71MB/s]
PS E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> canvassyncer -d
Getting course IDs...
Get 0 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
PS E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> canvassyncer -d
Getting course IDs...
Get 0 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
PS E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> canvassyncer -d
Getting course IDs...
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
Get 0 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
PS E:\msys64\mingw64\lib\python3.10\site-packages\canvassyncer> canvassyncer -d
Getting course IDs...
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
Get 1 available courses!
Finding files on canvas...
Get 0 files!
All local files are synced!
```

**Comment by wznmickey** [comment]
Can you try to remove all the courseCodes and make sure all the courseIds are valid?
Like 
```
{
    "canvasURL": "https://jicanvas.com",
    "token": "omitted",
    "courseCodes": [],
    "courseIDs": [
        170,
        77,
        130,
        113,
        168,
        164
    ],
    "downloadDir": "omitted",
    "filesizeThresh": 250.0
}
```

**Comment by Yushu-He** [comment]
```
~>canvassyncer -d
Getting course IDs...
Get 6 available courses!
Finding files on canvas...
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
JSONDecodeError. Retry. 1 times.
Get 2 files!
All local files are synced!
```
This method works, thank you so much
